#!/usr/bin/expect -f
spawn /usr/local/endeca/ToolsAndFrameworks/11.3.1.5.0/credential_store/bin/manage_credentials.sh add --config /usr/local/endeca/ToolsAndFrameworks/11.3.1.5.0/server/workspace/credential_store/jps-config.xml --mapName endecaToolsAndFrameworks --user admin --key ifcr --type password

expect "password"
send -- "Admin123\r"
expect "password"
send -- "Admin123\r"
expect "replace"
send -- "yes\r"
expect eof
